const date =  document.getElementById("date")
const month =  document.getElementById("month")
const year =  document.getElementById("year")
const gender =  document.getElementById("gender")
const form =  document.getElementById("form")
